version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: farmfresh
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuserpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql:ro   # put converted Postgres SQL here
    ports:
      - "5433:5432"   # host:container to avoid collisions; inside containers use 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d farmfresh"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    restart: always
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DRIVER: pgsql
      DB_HOST: db
      DB_NAME: farmfresh
      DB_USER: appuser
      DB_PASSWORD: appuserpassword
      DB_PORT: 5432
      PHP_ERROR_REPORTING: E_ALL

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
  postgres-data:
# End of docker-compose.yml